// Fill out your copyright notice in the Description page of Project Settings.


#include "RaceMenu.h"
#include "RaceMenuEntryObject.h"

void URaceMenu::AddEntry(USkeletalMeshComponent* mesh, FName morphTarget, FString name, float minValue, float maxValue, float defaultValue) {

	URaceMenuEntryObject* entry = NewObject<URaceMenuEntryObject>();
	entry->Name = FText::FromString(name);
	entry->MorphTarget = morphTarget;
	entry->MaxValue = maxValue;
	entry->MinValue = minValue;
	entry->DefaultValue = defaultValue;
	entry->Value = mesh->GetMorphTarget(morphTarget);
	entry->Mesh = mesh;
	ControlListView->AddItem(entry);
}
void URaceMenu::setSliderValues(AGameCharacter* character) {
	USkeletalMeshComponent * mesh = character->GetMesh();
	AddEntry(mesh, TEXT("pJCMPelvisFwd_25"), TEXT("Pelvis Forward"), -0.25, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_1"), TEXT("Breast Preset 1"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_02"), TEXT("Breast Preset 02"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_03"), TEXT("Breast Preset 03"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_04"), TEXT("Breast Preset 04"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_05"), TEXT("Breast Preset 05"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_06"), TEXT("Breast Preset 06"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_07"), TEXT("Breast Preset 07"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_08"), TEXT("Breast Preset 08"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_09"), TEXT("Breast Preset 09"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_10"), TEXT("Breast Preset 10"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_11"), TEXT("Breast Preset 11"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Breast_Preset_12"), TEXT("Breast Preset 12"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("CTRLBreastsImplants"), TEXT("Breast Implants"), -1.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("CTRLBreastsNatural"), TEXT("Breasts Natural"), -0.25, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsCleavage"), TEXT("Cleavage"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsDiameter"), TEXT("Breast Diameter"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsDownwardSlope"), TEXT("Breast Downward"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsGone"), TEXT("Breast Gone"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsHeavy"), TEXT("Breast Heavy"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsPerkSide"), TEXT("Breast Perky"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsSmall"), TEXT("Breast Small"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsUnderCurve"), TEXT("Breast Under"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMBreastsUpwardSlope"), TEXT("Breast Upward"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("L3D_Nails1"), TEXT("Nails 1"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("L3D_Nails2"), TEXT("Nails 2"), -0.3499999940395355, 1.0, 0.0);
	AddEntry(mesh, TEXT("L3D_Nails3"), TEXT("Nails 3"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("L3D_Nails4"), TEXT("Nails 4"), -0.4000000059604645, 1.149999976158142, 0.0);
	AddEntry(mesh, TEXT("PBMNailsLength"), TEXT("Nails Length"), -0.30000001192092896, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMBodySize"), TEXT("Body Size"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMBodyTone"), TEXT("Body Tone"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMBodybuilderDetails"), TEXT("Bodybuilder Details"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMBodybuilderSize"), TEXT("Bodybuilder Size"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMEmaciated"), TEXT("Emaciated"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMFitnessDetails"), TEXT("Fitness Details"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMFitnessSize"), TEXT("Fitness Size"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMHeavy"), TEXT("Heavy"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMHeight"), TEXT("Height"), -1.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMPearFigure"), TEXT("Pear Figure"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMThin"), TEXT("Thin"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("FBMVoluptuous"), TEXT("Voluptuous"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPregnant"), TEXT("Pregnant"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_01"), TEXT("Thicc 01"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_02"), TEXT("Thicc 02"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_03"), TEXT("Thicc 03"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_04"), TEXT("Thicc 04"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_05"), TEXT("Thicc 05"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_06"), TEXT("Thicc 06"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_07"), TEXT("Thicc 07"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_08"), TEXT("Thicc 08"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_09"), TEXT("Thicc 09"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_10"), TEXT("Thicc 10"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_11"), TEXT("Thicc 11"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Thicc_12"), TEXT("Thicc 12"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMCollarboneDetail"), TEXT("Collarbone Detail"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMCostalAngleArched"), TEXT("Costal Angle Arched"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMCostalAnglePointed"), TEXT("Costal Angle Pointed"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMHipBoneSize"), TEXT("Hip BoneS ize"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLineaAlbaDepth"), TEXT("Linea Alba Depth"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLoveHandles"), TEXT("Love Handles"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMNavelDepth"), TEXT("Navel Depth"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMNavelHorizontal"), TEXT("Navel Horizontal"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMNavelOut"), TEXT("Navel Out"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMRectusOuterDetail"), TEXT("Rectus Outer Detail"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMRectusWidth"), TEXT("Rectus Width"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMRibcageSize"), TEXT("Ribcage Size"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMSternumDepth"), TEXT("Sternum Depth"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMStomachSoften"), TEXT("Stomach Soften"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("SCR_Belly_Fat"), TEXT("Belly Fat"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("SCR_Calf_Thickness"), TEXT("Calf Thickness"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("Foot_Shapely"), TEXT("Foot Shape"), -1.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_01"), TEXT("Booty 01"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_02"), TEXT("Booty 02"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_03"), TEXT("Booty 03"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_04"), TEXT("Booty 04"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_05"), TEXT("Booty 05"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_06"), TEXT("Booty 06"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_07"), TEXT("Booty 07"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_08"), TEXT("Booty 08"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_09"), TEXT("Booty 09"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_10"), TEXT("Booty 10"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_11"), TEXT("Booty 11"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Booty_12"), TEXT("Booty 12"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("Aelis_Nipples"), TEXT("Aelis Nipples"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMAreolaeDepth"), TEXT("Areolae Depth"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMAreolaeDiameter"), TEXT("Areolae Diameter"), -0.25, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMAreolaePerk"), TEXT("Areolae Perk"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("BJ_Cheeks_-_Balloon_Left"), TEXT("Cheeks - Balloon Left"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("BJ_Cheeks_-_Balloon_Right"), TEXT("Cheeks - Balloon Right"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("BJ_Cheeks_-_Suck_Left"), TEXT("Cheeks - Suck Left"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("BJ_Cheeks_-_Suck_Right"), TEXT("Cheeks - Suck Right"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("BJ_Throat_-_Bulge_02"), TEXT("Throat - Bulge 02"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("PBMG8FAnusOpen"), TEXT("Anus Open"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMAnusOpen"), TEXT("Anus Open 2"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMClitoralHoodDepth"), TEXT("Clitoral Hood Depth"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMClitoralHoodLeftRight"), TEXT("Clitoral Hood Tilt"), -1.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMClitoralHoodLength"), TEXT("Clitoral Hood Length"), -1.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMClitoralHoodRiseDown"), TEXT("Clitoral Hood Rise"), -1.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMClitoralHoodSize"), TEXT("Clitoral Hood Size"), -0.5, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensClose01"), TEXT("Vagina Close 01"), 0.0, 1.2000000476837158, 0.0);
	AddEntry(mesh, TEXT("PBMGensClose02"), TEXT("Vagina Close 02"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensClose03"), TEXT("Vagina Close 03"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensOpen01"), TEXT("Vagina Open 01"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensOpen02"), TEXT("Vagina Open 02"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensOpen03"), TEXT("Vagina Open 03"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensPosition"), TEXT("Vagina Position"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensSize01"), TEXT("Vagina Size 01"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensSize02"), TEXT("Vagina Size 02"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMGensSize03"), TEXT("Vagina Size 03"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMajoraOpenL"), TEXT("Labia Majora Open (L)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMajoraOpenR"), TEXT("Labia Majora Open (R)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMajoraStyle01"), TEXT("Labia Majora Style 1"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMajoraStyle02"), TEXT("Labia Majora Style 2"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraEversion"), TEXT("Labia Minora Eversion"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraOffset01"), TEXT("Labia Minora Offset 1"), -1.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraOffset02"), TEXT("Labia Minora Offset 2"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraOffset03"), TEXT("Labia Minora Offset 3"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraOpenL"), TEXT("Labia Minora Open (L)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraOpenR"), TEXT("Labia Minora Open (R)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraPosition"), TEXT("Labia Minora Position"), 0.0, 1.2000000476837158, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraSize"), TEXT("Labia Minora Size" ), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraStyle01"), TEXT("Labia Minora Style 1"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraStyle02"), TEXT("Labia Minora Style 2"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraStyle02Eversion"), TEXT("Labia Minora Style 2 Eversion"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraStyle03"), TEXT("Labia Minora Style 3"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraStyle03Eversion"), TEXT("Labia Minora Style 3 Eversion"), 0.0, 1.5, 0.0);
	AddEntry(mesh, TEXT("PBMLabiaMinoraStyle04"), TEXT("Labia Minora Style 4"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMajoraLowerLeft"), TEXT("Pull Labia Maj. Low (L)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMajoraLowerRight"), TEXT("Pull Labia Maj. Low (R)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMajoraMiddelLeft"), TEXT("Pull Labia Maj. Mid (L)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMajoraMiddelRight"), TEXT("Pull Labia Maj. Mid (R)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMajoraUpperLeft"), TEXT("Pull Labia Maj. Up (L)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMajoraUpperRight"), TEXT("Pull Labia Maj. Up (R)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMinoraMiddelLeft"), TEXT("Pull Labia Min. Mid (L)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMinoraMiddelRight"), TEXT("Pull Labia Min. Mid (R)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMinoraUpperLeft"), TEXT("Pull Labia Min. Up (L)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("PBMPullLabiaMinoraUpperRight"), TEXT("Pull Labia Min. Up (R)"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("SpaceBetweenLegs"), TEXT("Space Between Legs"), 0.0, 1.0, 0.0);
	AddEntry(mesh, TEXT("ThinghsThicc"), TEXT("Thick Thighs"), 0.0, 1.0, 0.0);
	
}
